# Generated by Django 5.1.15 on 2026-09-15 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Identifiant unique (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Créateur (Admin)')),
                ('members', models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Membres assignés')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du sous-projet')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Identifiant unique (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='projects.project', verbose_name='Projet parent')),
            ],
            options={
                'verbose_name': 'Sous-projet',
                'verbose_name_plural': 'Sous-projets',
                'ordering': ['created_at'],
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Intitulé de l'accès")),
                ('service_url', models.CharField(blank=True, max_length=255, verbose_name='URL / Serveur / Hôte')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Identifiant / Login')),
                ('password', models.CharField(max_length=255, verbose_name='Mot de passe / Clé secrète')),
                ('notes', models.TextField(blank=True, verbose_name="Notes / Consignes d'accès")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='projects.subproject')),
            ],
            options={
                'verbose_name': 'Accès & Mot de passe',
                'verbose_name_plural': 'Accès & Mots de passe',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la colonne')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.subproject')),
            ],
            options={
                'verbose_name': 'Colonne Kanban',
                'verbose_name_plural': 'Colonnes Kanban',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la tâche')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.kanbancolumn')),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.subproject')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-created_at'],
            },
        ),
    ]
