# Generated by Django 5.1.15 on 2026-09-15 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_task_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document / fichier')),
                ('url', models.URLField(max_length=500, verbose_name='Lien URL')),
                ('resource_type', models.CharField(choices=[('document', 'Documentation'), ('file', 'Fichier / Cloud'), ('design', 'Maquette / Design'), ('repo', 'Dépôt / Code'), ('other', 'Autre lien')], default='document', max_length=20, verbose_name='Type de ressource')),
                ('description', models.TextField(blank=True, verbose_name='Description / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project', verbose_name='Projet')),
                ('subproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.subproject', verbose_name='Sous-projet (optionnel)')),
            ],
            options={
                'verbose_name': 'Document & Fichier',
                'verbose_name_plural': 'Documents & Fichiers',
                'ordering': ['-created_at'],
            },
        ),
    ]
