# Generated by Django 5.1.15 on 2026-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='entry_type',
            field=models.CharField(choices=[('file', 'Fichier téléversé'), ('url', 'Lien web / URL externe')], default='file', max_length=10, verbose_name="Type d'entrée"),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/%Y/%m/', verbose_name='Fichier téléversé'),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Taille en octets'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='resource_type',
            field=models.CharField(choices=[('document', 'Documentation / PDF'), ('file', 'Fichier / Archive'), ('design', 'Design / Maquettes'), ('repo', 'Dépôt / Code source'), ('other', 'Autre document')], default='document', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nom du document / fichier'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Lien URL externe'),
        ),
    ]
