# Generated by Django 5.1.15 on 2026-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectresource_entry_type_projectresource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresource',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du document / fichier'),
        ),
    ]
