# Generated by Django 5.2.17 on 2026-09-16 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_encrypt_existing_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectresource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document / Ressource', 'verbose_name_plural': 'Documents & Ressources'},
        ),
        migrations.RemoveField(
            model_name='projectresource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectresource',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='projectresource',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='projectresource',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='projectresource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='projects.task', verbose_name='Tâches préalables requises'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Créé par (Admin)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_projects', to=settings.AUTH_USER_MODEL, verbose_name="Membres de l'équipe"),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='description',
            field=models.TextField(blank=True, verbose_name='Notes / Description'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_resources/%Y/%m/', verbose_name='Fichier uploadé'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='resource_type',
            field=models.CharField(choices=[('document', 'Document'), ('file', 'Fichier'), ('link', 'Lien externe'), ('design', 'Maquette (Figma, etc.)'), ('repo', 'Dépôt Git / Code'), ('other', 'Autre')], default='document', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.subproject', verbose_name='Sous-projet'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre du document'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='url',
            field=models.URLField(blank=True, verbose_name='Lien externe'),
        ),
    ]
